"""add deleted_at to entries

Revision ID: 5df41c2a8080
Revises: ee602c28ff5d
Create Date: 2026-08-20 20:40:10.372147

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5df41c2a8080"
down_revision: str | Sequence[str] | None = "ee602c28ff5d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entries", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("entries", "deleted_at")
    # ### end Alembic commands ###
