"""add user_id to entries

Revision ID: ee602c28ff5d
Revises: fed9822ae4a4
Create Date: 2026-08-20 17:32:46.149065

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee602c28ff5d"
down_revision: str | Sequence[str] | None = "fed9822ae4a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entries", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_entries_user_id"), "entries", ["user_id"], unique=False)
    op.create_foreign_key(None, "entries", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "entries", type_="foreignkey")
    op.drop_index(op.f("ix_entries_user_id"), table_name="entries")
    op.drop_column("entries", "user_id")
    # ### end Alembic commands ###
